project:
  type: website

website:
  title: DataInk Drinkers
  navbar:
    right:
      - icon: github
        href: https://github.com/INFO526-DataViz/project-01-DataInk-Drinkers
    left:
      - text: Project
        href: index.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Presentation
        href: presentation.qmd
      - text: About
        href: about.qmd
    logo: images\ufologo.png
  favicon: images\ufologo.png

format:
  html:
    theme:
      light: flatly
      dark: darkly
      
    toc: true

execute:
  freeze: auto
